
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/kite-traders1/myproj
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 100
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - location: ./run.sh
      timeout: 100
      runas: ubuntu
